# This actions updates the release branch when tag prod is pushed.
name: Tab based Deployment 

# Configure to deploy on tag push
on:
  push:
    tags:
      - "prod"

# Adds permissions.
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site (root folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create release date tag
        run: |
          DATE=$(date +'%Y-%m-%d-%H%M')
          TAG_NAME="release-$DATE"
          echo "Creating tag $TAG_NAME on release branch"
          git tag -a $TAG_NAME -m "Release on $DATE"
          git push origin $TAG_NAME